# Generated by Django 5.0.6 on 2024-06-06 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chaiaurDjango\\myapp')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KW', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI')], max_length=2)),
            ],
        ),
    ]
