# Generated by Django 5.0.6 on 2024-06-06 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KW', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
